### PR TITLE
Added Bayesian Hyperparameter tuning for all DN on Audition tasks (Issue #31)

### PR DESCRIPTION
**Pull request by adwaykanhere**
This PR will address part of Issue #31 and have the following changes:

- Closed adding Bayesian hyperparameter tuning of the Audition data using Pytorch's Ax library and Raytune. 
- Fixed adding a separate file- fsdk18preprocess.py for all preprocessing steps required to run DN benchmarks on audition. This is necessary to run fsdk18.py and fsdk18tuning.py scripts. 
- Ensured that the ratio of sample sizes for audition is consistently 2:1:1 for all the class combinations when running benchmarks with and without tuning. 
- Resolved to remove any unnecessary functions in the audition toolbox

Library conflicts: 
Raytune needs to be version 1.11.0 and not later

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
You need to optimize the requirements and dependencies. Why removing the versions?

Say if script A imports package I, and script B imports script A, then script B should not import package I. Remove the duplications to make the code more robust.

Additionally, I don't see why there's an `fsd18k` and an `fsd18ktuning`. Leave the updated one and name it `fsd18k`.

**Review by PSSF23 — COMMENTED** [review]
`fsdk18preprocess` is not necessary as a separate file. Put the function inside `toolbox`.

**Comment by adwaykanhere** [comment]
all changes updated

**Review by PSSF23 — COMMENTED** [review]
I don't understand why you downgraded `opencv-python` and use a different format for `torch` packages (checks not passed). Also there is no `sklearn` pacakge name in `pip`.

**Comment by adwaykanhere** [comment]
Sorry, the changes have been fixed.

**Review by PSSF23 — COMMENTED** [review]
Did you use `botorch` at all?

**Comment by adwaykanhere** [comment]
Botorch is a requirement for Ax. [Reference](https://ax.dev/docs/installation.html)

**Pull request merged**
